tap "caskroom/versions"
tap "git-chglog/git-chglog"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "kyoshidajp/ghkw"
tap "mono0926/license-plist"
tap "peripheryapp/periphery"
tap "tidwall/jj"
tap "zaquestion/tap"
brew "bat"
brew "bitrise"
brew "fontconfig"
brew "carthage"
brew "clang-format"
brew "composer"
brew "dep"
brew "exa"
brew "ffmpeg"
brew "fish"
brew "ghq"
brew "gibo"
brew "giflossy"
brew "git"
brew "hub"
brew "hugo"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "infer"
brew "ios-deploy"
brew "jenv"
brew "jq"
brew "mas"
brew "mysql"
brew "neovim"
brew "peco"
brew "php-cs-fixer"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "sourcekitten"
brew "swiftlint"
brew "tmux"
brew "watchman"
brew "yarn"
brew "yq"
brew "zplug"
brew "git-chglog/git-chglog/git-chglog"
brew "kyoshidajp/ghkw/ghkw"
brew "mono0926/license-plist/license-plist"
brew "tidwall/jj/jj"
brew "zaquestion/tap/lab"
cask "agenda"
cask "font-fira-code"
cask "peripheryapp/periphery/periphery"
mas "1Password", id: 443987910
mas "Bear", id: 1091189122
mas "CotEditor", id: 1024640650
mas "DesiGN Templates for Keynote", id: 555935825
mas "GIPHY CAPTURE", id: 668208984
mas "Just Color Picker", id: 886547068
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "PicGIF Lite", id: 844918735
mas "Spark", id: 1176895641
mas "Toolbox for Keynote -Templates", id: 582635628
