local global = require("core.global")

vim.opt.termguicolors = true
vim.opt.errorbells = true
vim.opt.visualbell = true
vim.opt.hidden = true
vim.opt.fileformats = "unix,mac,dos"
vim.opt.magic = true
vim.opt.virtualedit = "block"
vim.opt.encoding = "utf-8"
vim.opt.viewoptions = "folds,cursor,curdir,slash,unix"
vim.opt.sessionoptions = "curdir,help,tabpages,winsize"
vim.opt.clipboard = "unnamedplus"
vim.opt.wildignorecase = true
vim.opt.wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**"
vim.opt.backup = true
vim.opt.swapfile = false
vim.opt.undodir = global.cache_dir .. "undo/"
vim.opt.directory = global.cache_dir .. "swap/"
vim.opt.viewdir = global.cache_dir .. "view/"
vim.opt.spellfile = global.cache_dir .. "spell/en.uft-8.add"
vim.opt.history = 2000
vim.opt.shada = "!,'300,<50,@100,s10,h"
vim.opt.backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim"
vim.opt.smarttab = true
vim.opt.shiftround = true
vim.opt.timeout = true
vim.opt.ttimeout = true
-- You will feel delay when you input <Space> at lazygit interface if you set it a positive value like 300(ms).
vim.opt.timeoutlen = 0
vim.opt.ttimeoutlen = 0
vim.opt.updatetime = 100
vim.opt.redrawtime = 1500
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.infercase = true
vim.opt.incsearch = true
vim.opt.wrapscan = true
vim.opt.complete = ".,w,b,k"
vim.opt.inccommand = "nosplit"
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --hidden --vimgrep --smart-case --"
vim.opt.breakat = [[\ \  ;:,!?]]
vim.opt.startofline = false
vim.opt.whichwrap = "h,l,<,>,[,],~"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.switchbuf = "useopen"
vim.opt.backspace = "indent,eol,start"
vim.opt.diffopt = "filler,iwhite,internal,algorithm:patience"
vim.opt.wildmode = "longest:full,full"
vim.opt.completeopt = "menuone,noselect"
vim.opt.jumpoptions = "stack"
vim.opt.showmode = false
vim.opt.shortmess = "aoOTIcF"
vim.opt.scrolloff = 2
vim.opt.sidescrolloff = 5
vim.opt.mousescroll = "ver:3,hor:6"
vim.opt.foldlevelstart = 99
vim.opt.ruler = true
vim.opt.cursorline = true
vim.opt.cursorcolumn = true
vim.opt.list = true
vim.opt.showtabline = 2
vim.opt.winwidth = 30
vim.opt.winminwidth = 10
-- vim.opt.pumblend = 10
vim.opt.pumheight = 15 -- 10
vim.opt.helpheight = 12
vim.opt.previewheight = 12
vim.opt.showcmd = false
-- vim.opt.cmdheight = 0 -- 0, 1, 2
-- vim.opt.cmdwinheight = 5
vim.opt.equalalways = false
vim.opt.laststatus = 3
vim.opt.display = "lastline"
vim.opt.showbreak = "↳  "
vim.opt.listchars = "tab:>-,trail:-,extends:>,precedes:<,nbsp:%,eol:↲"
-- vim.opt.winblend = 10
vim.opt.autoread = true
vim.opt.autowrite = true
vim.opt.undofile = true
vim.opt.synmaxcol = 2500
vim.opt.formatoptions = "1jcroql"
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.breakindentopt = "shift:2,min:20"
vim.opt.wrap = false
vim.opt.linebreak = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.foldenable = true
vim.opt.signcolumn = "yes"
vim.opt.conceallevel = 0
vim.opt.concealcursor = "niv"

if vim.fn.has("nvim-0.8") == 1 then
    vim.opt.cmdheight = 0
    vim.opt.backupdir = vim.fn.stdpath("state") .. "/backup"
end

if vim.fn.has("nvim-0.9.0") == 1 then
    vim.opt.splitkeep = "screen"
    vim.o.shortmess = "filnxtToOFWIcC"
end
