# 非同期シンタックスチェック
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    set nocompatible
    filetype off
    let &runtimepath.=',~/.vim/bundle/ale'
    filetype plugin on

    let g:ale_sign_column_always = 1
    let g:ale_lint_on_enter = 0
    let g:ale_lint_on_save = 1
    let g:ale_lint_on_text_changed = 0
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 1
    let g:ale_open_list = 1
    let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
'''

# ========== Plist ==========

[[plugins]]
repo = 'darfink/vim-plist'
on_ft = ['plist']

